CREATE DATABASE IF NOT EXISTS lulububu_rgb_challenge;

USE lulububu_rgb_challenge;

CREATE TABLE IF NOT EXISTS colors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  red_value TINYINT UNSIGNED NOT NULL,
  green_value TINYINT UNSIGNED NOT NULL,
  blue_value TINYINT UNSIGNED NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);